# Generated by Django 4.2.13 on 2026-04-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('att_status', models.CharField(choices=[('on_time', 'Vaqtida'), ('late', 'Kechikdi')], default='on_time', max_length=10)),
                ('method', models.CharField(choices=[('faceid', 'FaceID'), ('qr', 'QR-kod')], default='faceid', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Davomat',
                'verbose_name_plural': 'Davomatlar',
                'db_table': 'attendance',
                'ordering': ['-date', '-check_in'],
            },
        ),
    ]
